apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy-task-backend
  name: deploy-task-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: task-backend
  strategy: {}
  template:
    metadata:
      labels:
        app: task-backend
    spec:
      containers:
      - image: bhabanisn/task-backend
        name: task-backend-con
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
