apiVersion: v1
kind: Service
metadata:
  annotations:
    #networking.gke.io/load-balancer-type: "Internal"
  labels:
    app: deploy-task-frontend
  name: task-frontend-lb-svc-static-ip
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: task-frontend
  type: LoadBalancer
  loadBalancerIP: 34.41.166.254
